twitter_api:
  consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %>
  access_token_secret: <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>
  bearer_token: <%= ENV["TWITTER_BEARER_TOKEN"] %>
  
youtube_api:
  main_key: <%= ENV["YOUTUBE_TOKEN"] %>
  
twitch_api:
  client_id: <%= ENV["TWITCH_ID"] %>
  client_secret: <%= ENV["TWITCH_SECRET"] %>