twitter_api:
  consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %>
  access_token_secret: <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>
  bearer_token: <%= ENV["AAAAAAAAAAAAAAAAAAAAAEu4RAEAAAAAx%2BlZgva%2BrE2dJSc2VpuMX6Ies%2FU%3DveENjBMGonT8voLgl1wPZsw5DGNdREXjhs7koyL0Sgt9phcDvi"]